name: Business_Card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/Ayan Hafeez.jpg

  fonts:
    - family: Arkhip
      fonts:
        - asset: fonts/Arkhip-Regular.ttf
    - family: Moon2.0
      fonts:
        - asset: fonts/Moon2.0-Regular.otf
